[language-server.nu-lint]
command = "cargo"
args = ["run",  "--", "--lsp"]

[language-server.rust-analyzer.config]
procMacro = true
cachePriming.enable = true
cargo = { allFeatures = true, allTargets = true }
check.command = "clippy"
completion.postfix.enable = false
diagnostics.experimental.enable = true


[language-server.nu]
command = "nu"
args = ["--lsp", "--no-config-file"]

[[language]]
name = "nu"
language-servers = ["nu-lint", "nu"]
